version: '3.8'

services:
  db:
    image: postgres:15
    container_name: news_postgres
    environment:
      POSTGRES_USER: newsuser
      POSTGRES_PASSWORD: newspass
      POSTGRES_DB: newsdb
    ports:
      - "5432:5432"
    volumes:
      - news_data:/var/lib/postgresql/data

volumes:
  news_data:
